// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ZwNuRDmYvepLbuRXE-ZmLDBUziv6pAY',
    appId: '1:525155902751:web:8b3659c92ab0d6093b7c2a',
    messagingSenderId: '525155902751',
    projectId: 'nation-job-connect',
    authDomain: 'nation-job-connect.firebaseapp.com',
    storageBucket: 'nation-job-connect.appspot.com',
    measurementId: 'G-VXZGQFXT49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR4_J0oyOqTppL3-jss1lkb0z9XXLZf20',
    appId: '1:525155902751:android:0646bcc5cf35aed93b7c2a',
    messagingSenderId: '525155902751',
    projectId: 'nation-job-connect',
    storageBucket: 'nation-job-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFH6xbUeH4R82uDdwhUF9PWzGnDoDnEvs',
    appId: '1:525155902751:ios:eac4bc6d24acd6ef3b7c2a',
    messagingSenderId: '525155902751',
    projectId: 'nation-job-connect',
    storageBucket: 'nation-job-connect.appspot.com',
    iosBundleId: 'com.worldsmartapps.nationJobConnectAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFH6xbUeH4R82uDdwhUF9PWzGnDoDnEvs',
    appId: '1:525155902751:ios:52be10d2044bc1033b7c2a',
    messagingSenderId: '525155902751',
    projectId: 'nation-job-connect',
    storageBucket: 'nation-job-connect.appspot.com',
    iosBundleId: 'com.worldsmartapps.nationJobConnectAdmin.RunnerTests',
  );
}
